package cn.itamt.utils.inspector.plugins.deval
{
	import cn.itamt.utils.BmdStrConverter;
	import cn.itamt.utils.inspector.lang.InspectorLanguageManager;
	import cn.itamt.utils.inspector.ui.InspectorIconButton;

	import flash.display.BitmapData;

	/**
	 * DEval plugin's icon button.
	 * @author tamt
	 */
	public class DEvalButton extends InspectorIconButton
	{
		protected static var icon:BitmapData;
		
		public function DEvalButton()
		{
			if(icon == null){
				icon = BmdStrConverter.str2bmd("AAAAJAAAABABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASvzLg9r9u1n//6Yj//+YAP//rRXb/sk/RfvIbwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADH6y4Kx/agu9P2dD///nwD//6IA//+fAP/PiCb/X1WI9K18Taz9siEz+s2CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY/zGdvj+oR///5gA//WXA//CgDb/bmB3/0BHpP8ALtb/ACTp/75/L///nQD4/qEeX/zEcwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJ+86F//+kIP//lwD/+J0E/zdEqv8VM8v/gGZs/39nZ/8AKd//EDbG/+SSFf//nQD//5UA//+jH0L70YsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnj4+Pc/aoy//+VAP//mwD/75QM/6N1Tf/tlQ3//6wA/4JnZv8AJOr/LkOs//2cAv//mgD//5kA//+VAMz+qzEM6urqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEz7uFD//5sJ//+YAP//mQD//5kA//+gAP//mwD//58A/09Rkv8AI+v/VFSK//+hAP//mQD//5kA//+YAPr+mwhk/L9hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ79rTX//5gD//+ZAP//mQD//5kA//+ZAP//mgD/+pkD/yhCr/8AJen/gmdp//+iAP//mQD//5kA//+ZAP//mADw/rA+AAAAAAbU1NQ7VnnYXzZb1FgpUdAoZobfAAAAACdpg94yQmbWHU9y3EVnhd4FzMzMAAAAABR/mdlFZIHeGH+V30Jkf+Adco3cAAAAAKb9mwj//5kA//+ZAP//mQD//5kA//+ZAP//nQD/3o4b/wg1x/8AKd//rHlE//+hAP//mQD//5kA//+ZAP//mQD//5wHMIWf5MQ4XNT/EzvO/xI+z/8lTdL9Fz/OZD1j1kCLn+fwKFDR8A89zptMcNsFzMzMAAAAACuyxO3xN1zU6ww4zf0vVtRFkKbpAAAAAKb9mwj//5kA//+ZAP//mQD//5kA//+ZAP//oQD/tH49/wAr2v8BMNH/1Ykh//+eAP//mQD//5kA//+ZAP//mQD//5wHU3iT4+sQPM3/ACzK+zxj1uZphd/xI0rQ6RE8zgAAAAC3KlPS/wo3zR1GatMAAAAAAAAAAAnj4+PFNFvV/wApytscSNAEv7+/AAAAAJ79rTX//5gD//+ZAP//mQD//5kA//+ZAP//ogD/jmxb/wAm5f8dO73/75YL//+cAP//mQD//5kA//+ZAP//mADx/bA+AAAAALUsVNL/BzXM+hE+zuY+YdbyIEXOrDJX1AAAAAC6KlPT/ws4zSU3YNYAAAAAqTNa1eEdSNDvHknQ0zNZ1P8HNMxFXIHeAAAAAEn7uU3//5wJ//+YAP//mQD//5kA//+ZAP//ogD/YlmA/wAk6f8+SZ///54A//+aAP//mQD//5kA//+YAPr+mwlh/L1eAAAAAMAnUNL2DDnMr0ls2f8FLsv3K1XSK8TQ7QAAAAC8LVTS/ws4zSJDadkAAAAAiTtj1vc4XdX7DDfL1xVDzv8AMMueNFrVAAAAAAOqqqrD/aIa//+XAP//mQD//5kA//+aAP/+ngD/O0ii/wAk6f9lW3z//6EA//+ZAP//mQD//5kA//+XALf9oxwCf39/AAAAAMApUdL+BzbME/Ly8rw8YNX/BDLMe1N22wAAAAC6LlXT/wU0zFJ5leO6NFrUki1W1fQUPs2uSWzZzTdc1vAOPc7pGETQDsjb7QAAAAA2+r1a//+iGv//lgD//54A//+lAP/ulQ3/DjbF/wAl5/+Ia2L//6oA//+gAP//mgD//5YA/f6hGTX6wGUAAAAAgniV498PPs34AzDKhFl63JRuiuD2AC3K8BI/zplYeNzbDz3O8wAuytxAZdf/GEHQ/w42zLU8YdYAAAAAHtTd9uAfSdD9ATDLkiFN0gAAAAAAAAAAX/zEcev9og3/uHs3/4RoYP9QVI3/CDHQ/wox0P8xR6f/fmhm/4toXP/vkwvs/aARWvzDbAAAAAAAAAAAL2yI3h4AIsMbABzGIjRh0hpFYtgbABzGHQAawS0oT9IfACHFGgAdxCIWQ9JDa4ngRld42gJ/f38AAAAABgAqqhwALsgdACPBHwApxQAAAAAAAAAAAAAAACn5012xy5VT9MOFQP/WjCL/5ZET/+WSE//cjhv/yIMs9MOEPKzzpjUr+cprAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASvzgXbv+uDf//6oZ//+bAP//qxi5/bg0RvveVAAAAAAAAAAAAAAAAAAAAAAAAAAA");
			}
			
			super(icon);
			
			this.tip = InspectorLanguageManager.getStr("DEval");
			this.setSize(40, 23);
		}
	}
}
